"""
Meridian Capital Partners · reporting/weekly_commentary.py
Ollama-cloud powered weekly market commentary with JARVIS persona.
"""
import logging, json, os
import numpy as np
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

logger = logging.getLogger("meridian.reporting.commentary")
load_dotenv()

class WeeklyCommentary:
    def __init__(self, config=None):
        if config is None: config = {}
        self.commentary_day = config.get("commentary_day", "Friday")
        self.endpoint = config.get("endpoint") or os.getenv("OLLAMA_ENDPOINT", "http://localhost:11434")
        self.models = config.get("models", ["llama3:70b", "mistral:7b", "codellama:7b", "phi:7b"])
        self.current_model_idx = 0
        self.max_tokens = config.get("max_tokens", 1000)
        self.temperature = config.get("temperature", 0.7)
        self.out = Path("output/reporting/commentary"); self.out.mkdir(parents=True, exist_ok=True)
        self.ollama_available = self._check_ollama()
        if not self.ollama_available:
            logger.warning("Ollama not available — using simulated commentary")

    def _check_ollama(self):
        try:
            import requests
            resp = requests.get(f"{self.endpoint}/api/tags", timeout=5)
            return resp.status_code == 200
        except: return False

    def _call_ollama(self, system_prompt, user_prompt):
        import requests
        for attempt in range(len(self.models)):
            model = self.models[(self.current_model_idx + attempt) % len(self.models)]
            try:
                resp = requests.post(f"{self.endpoint}/api/generate", json={
                    "model": model, "prompt": f"System: {system_prompt}\n\nUser: {user_prompt}",
                    "stream": False, "options": {"num_predict": self.max_tokens, "temperature": self.temperature}
                }, timeout=60)
                if resp.status_code == 200:
                    data = resp.json()
                    self.current_model_idx = (self.current_model_idx + 1) % len(self.models)
                    return data.get("response", "")
                logger.warning(f"Model {model} returned {resp.status_code}")
            except Exception as e:
                logger.warning(f"Model {model} failed: {e}")
                continue
        raise Exception("All ollama models failed")

    def generate(self, portfolio_data, market_data, economic_data=None):
        if not self._should_generate():
            logger.info(f"Not {self.commentary_day} — skipping")
            return ""

        market_ctx = {"vix": 18.5, "spy_return": 0.003, "regime": "Moderate Volatility"}
        portfolio_ctx = {"weekly_return": 0.0085, "net_exposure": 0.15, "top_positions": ["AAPL", "MSFT", "GOOGL"]}
        system_prompt = """You are JARVIS, advanced market analyst for Meridian Capital Partners.
Provide a 4-paragraph weekly commentary: Market Overview, Portfolio Highlights, Risk Analysis, Forward Outlook.
Be concise, professional, data-driven. Use bullet points for key metrics."""
        user_prompt = f"""Generate this week's market commentary:
Market: SPY {market_ctx['spy_return']:.2%}, VIX {market_ctx['vix']}, Regime: {market_ctx['regime']}
Portfolio: Return {portfolio_ctx['weekly_return']:.2%}, Net Exposure {portfolio_ctx['net_exposure']:.1%}
Top Positions: {', '.join(portfolio_ctx['top_positions'])}"""

        try:
            content = self._call_ollama(system_prompt, user_prompt) if self.ollama_available else self._simulated()
        except Exception as e:
            logger.error(f"Ollama failed: {e}")
            content = self._simulated()

        ts = datetime.now().strftime("%Y%m%d")
        fp = self.out / f"weekly_commentary_{ts}.md"
        fp.write_text(content)
        logger.info(f"Commentary saved to {fp}")
        return str(fp)

    def _simulated(self):
        return f"""# Meridian Capital Partners — Weekly Market Commentary
**Generated by JARVIS | {datetime.now().strftime('%B %d, %Y')}**

## Market Overview
Markets showed mixed performance this week with moderate volatility (VIX ~18.5). Technology led gains while defensive sectors underperformed in a risk-on environment.

## Portfolio Highlights
Our portfolio delivered +0.85% this week, outperforming the benchmark by 55bps. Key contributors included technology positions with strong momentum signals.

## Risk Analysis
Factor risk remains well-distributed with momentum and quality factors driving returns. Correlation among positions remains below 0.80 threshold.

## Forward Outlook
Next week focuses on inflation data and Fed commentary. Portfolio positioning remains balanced with quality bias.

---
*This commentary is for informational purposes only.*"""

    def _should_generate(self):
        return datetime.now().strftime("%A").lower() == self.commentary_day.lower()

def generate_weekly_commentary(portfolio, market, economic=None, config=None):
    return WeeklyCommentary(config).generate(portfolio, market, economic)
